export const iceCreamItem = [
  {
    name: "Chocolate Ice cream",
    id: "1",
    category: "Classic",
    img: "../../../public/menu/chocolate ice.png",
    discption: "Cono Biscuits and Chocolate ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Chocolate Gelato",
    id: "2",
    category: "Gelato",
    img: "../../../public/menu/cup chocolate.png",
    discption: "Chocolate Gelato ice cream in cup",
    price: 10,
    count: 100,
  },
  {
    name: "Chocolate stick",
    id: "3",
    img: "../../../public/menu/chocolate steck.png",
    category: "stick",
    discption: "Chocolate stick ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Strawberry ice cream",
    id: "4",
    category: "Classic",
    img: "../../../public/menu/strobarry ice.png",
    discption: "Cono Biscuits and Strawberry ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Strawberry Gelato",
    id: "5",
    category: "Gelato",
    img: "../../../public/menu/sreobarry cup.png",
    discption: "Strawberry Gelato ice cream in cup",
    price: 10,
    count: 100,
  },
  {
    name: "Strawberry stick",
    id: "6",
    img: "../../../public/menu/strobarry stick.png",
    category: "stick",
    discption: "Chocolate stick ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Vanilla ice cream",
    id: "7",
    category: "Classic",
    img: "../../../public/menu/vanella ice.png",
    discption: "Cono Biscuits and Vanilla ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Vanilla Gelato",
    id: "8",
    category: "Gelato",
    img: "../../../public/menu/vanella cup.png",
    discption: "Vanilla Gelato ice cream in cup",
    price: 10,
    count: 100,
  },
  {
    name: "Vanilla stick",
    id: "9",
    img: "../../../public/menu/vanella stek.png",
    category: "stick",
    discption: "Vanilla stick ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Caramel ice cream",
    id: "10",
    category: "Classic",
    img: "../../../public/menu/caramel ice.png",
    discption: "Cono Biscuits and Caramel ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Mix ice cream",
    id: "11",
    category: "Classic",
    img: "../../../public/menu/mix ice cream.png",
    discption:
      "Cono Biscuits and Mix ice cream (Vanilla, Strawberry, Chocolate)",
    price: 10,
    count: 100,
  },
  {
    name: "Pistachio stick",
    id: "12",
    img: "../../../public/menu/pstachio stik.png",
    category: "stick",
    discption: "Pistachio stick ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Pistachio Gelato",
    id: "13",
    category: "Gelato",
    img: "../../../public/menu/pstachio cup.png",
    discption: "Pistachio Gelato ice cream in cup",
    price: 10,
    count: 100,
  },
  {
    name: "Caramel stick",
    id: "14",
    img: "../../../public/menu/caramel stek.png",
    category: "stick",
    discption: "Caramel stick ice cream",
    price: 10,
    count: 100,
  },
  {
    name: "Caramel Gelato",
    id: "15",
    category: "Gelato",
    img: "../../../public/menu/caramel ice.png",
    discption: "Caramel Gelato ice cream in cup",
    price: 10,
    count: 100,
  },
  {
    name: "Pistachio Ice cream",
    id: "16",
    category: "Classic",
    img: "../../../public/menu/pistachio ice.png",
    discption: "Cono Biscuits and Pistachio ice cream",
    price: 10,
    count: 100,
  },
];
